// SPDX-License-Identifier: Apache-2.0
/// Renders the interface to PNG files, with no deck and no display.
///
/// Documentation screenshots go stale the moment somebody changes a colour, and
/// hand-captured ones cannot be regenerated by whoever reads the documentation
/// next. This renders the same QML the application does, driven by the same
/// scripted transport the tests use, so the images in README.md are reproducible
/// by anyone with a checkout -- and wrong only if the interface itself changed.

#include <ax310/FakeHidTransport.hpp>
#include <ax310/IClock.hpp>
#include <ax310/ILogger.hpp>
#include <ax310/Protocol.hpp>

#include <app/DeviceBridge.hpp>

#include <QDir>
#include <QEventLoop>
#include <QGuiApplication>
#include <QImage>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QQuickView>
#include <QQuickWindow>
#include <QTimer>

#include <cstdlib>
#include <print>

using namespace ax310;

namespace
{

/// One screen to capture.
struct Shot
{
    char const* source = ""; ///< QML to load.
    char const* file = "";   ///< Where to write it.
    int width = 0;
    int height = 0;
    bool isWindow = false;   ///< Main.qml is rooted in ApplicationWindow; the panel is not.
    bool effects = false;    ///< Put the panel on its effects page first.
};

constexpr std::array<Shot, 3> Shots { {
    { .source = "qrc:/qt/qml/AX310/App/gui/ScreenUI.qml",
      .file = "deck-panel.png",
      .width = 800,
      .height = 480,
      .isWindow = false },
    { .source = "qrc:/qt/qml/AX310/App/gui/ScreenUI.qml",
      .file = "deck-effects.png",
      .width = 800,
      .height = 480,
      .isWindow = false,
      .effects = true },
    { .source = "qrc:/qt/qml/AX310/App/gui/Main.qml",
      .file = "desktop.png",
      .width = 1000,
      .height = 840,
      .isWindow = true },
} };

/// Runs the event loop long enough for the meter ballistics to reach the signal.
///
/// They ramp on a 33 ms timer, so grabbing immediately catches every meter at
/// zero and photographs an interface that never exists in use.
void settle()
{
    QEventLoop loop;
    QTimer::singleShot(400, &loop, &QEventLoop::quit);
    loop.exec();
}

[[nodiscard]] QImage renderItem(app::DeviceBridge& bridge, Shot const& shot)
{
    QQuickView view;
    view.setResizeMode(QQuickView::SizeRootObjectToView);
    view.rootContext()->setContextProperty("ax310Device", &bridge);
    view.resize(shot.width, shot.height);
    view.setSource(QUrl(QString::fromUtf8(shot.source)));
    view.show();
    settle();
    return view.grabWindow();
}

[[nodiscard]] QImage renderWindow(app::DeviceBridge& bridge, Shot const& shot)
{
    QQmlApplicationEngine engine;
    engine.rootContext()->setContextProperty("ax310Device", &bridge);
    engine.load(QUrl(QString::fromUtf8(shot.source)));
    if (engine.rootObjects().isEmpty())
        return {};

    auto* const window = qobject_cast<QQuickWindow*>(engine.rootObjects().front());
    if (window == nullptr)
        return {};

    window->resize(shot.width, shot.height);
    window->show();
    settle();
    return window->grabWindow();
}

} // namespace

int main(int argc, char* argv[])
{
    qputenv("QT_QPA_PLATFORM", "offscreen");
    qputenv("QT_QUICK_BACKEND", "software");
    QQuickWindow::setGraphicsApi(QSGRendererInterface::Software);

    QGuiApplication const application { argc, argv };

    auto const directory = QString::fromUtf8(argc > 1 ? argv[1] : "docs/images");
    if (!QDir().mkpath(directory))
    {
        std::println(stderr, "could not create the output directory");
        return EXIT_FAILURE;
    }

    FakeHidTransport transport;
    ManualClock clock;
    NullLogger logger;
    transport.presentDevice(protocol::descriptorFor(DeviceMode::Control).productId,
                            { HidInterface { .path = "/dev/control", .interfaceNumber = 0 } });

    app::DeviceBridge bridge { transport, clock, logger };

    // A screenshot of an idle deck is six empty rings, which documents nothing.
    // The fake holds registers, so these go in the way the deck would hold them
    // and the driver reads them back over its ordinary connect path -- the image
    // then shows the same thing a real deck in this state would.
    constexpr std::array<int, KnobCount> CreatorSteps { 15, 8, 0, 20, 18, 13 };
    constexpr std::array<int, KnobCount> AudienceSteps { 12, 8, 0, 11, 20, 9 };
    for (auto const knob: AllKnobs)
    {
        transport.setRegister(protocol::levelAddressOf(protocol::Property::CreatorMixLevels, knob),
                              { static_cast<std::uint8_t>(CreatorSteps[indexOf(knob)]) });
        transport.setRegister(protocol::levelAddressOf(protocol::Property::AudienceMixLevels, knob),
                              { static_cast<std::uint8_t>(AudienceSteps[indexOf(knob)]) });
    }

    bridge.start();
    settle();

    // Fed continuously rather than once, because that is how the deck feeds them
    // and because a single event before the view exists is heard by nobody. The
    // meter ballistics then ramp exactly as they do in use.
    QTimer meters;
    meters.setInterval(33);
    QObject::connect(&meters, &QTimer::timeout, [&bridge] {
        bridge.onDeviceEvent(AudioMetersChanged { .levels = { 62, 9, 0, 71, 0, 34 } });
    });
    meters.start();

    for (auto const& shot: Shots)
    {
        // Driven through the bridge, the way the panel's own tile drives it, so
        // the screenshot is of a state the application can actually be in.
        bridge.setPanelShowsEffects(shot.effects);

        auto const image = shot.isWindow ? renderWindow(bridge, shot) : renderItem(bridge, shot);
        if (image.isNull())
        {
            std::println(stderr, "could not render {}", shot.source);
            return EXIT_FAILURE;
        }

        auto const path = directory + "/" + QString::fromUtf8(shot.file);
        if (!image.save(path, "PNG"))
        {
            std::println(stderr, "could not write {}", path.toStdString());
            return EXIT_FAILURE;
        }

        std::println("wrote {} ({}x{})", path.toStdString(), image.width(), image.height());
    }

    return EXIT_SUCCESS;
}
