// SPDX-License-Identifier: Apache-2.0
/// Writes the wire specification out of the tables that implement it.
///
/// A protocol document maintained by hand drifts, and this project has the scars
/// to prove it: the meters were described three different ways in three files at
/// once, and each description was written by somebody who believed it. So the
/// document is not written. It is **projected** from Protocol.hpp and Types.hpp,
/// and `--check` fails the test suite when the committed copy no longer matches
/// what the headers say.
///
/// The discipline that makes that work: **no number is typed in here.** The prose
/// below describes shape -- what a table's rows mean, how a frame is laid out --
/// and every address, length, offset, range and name is read from a constant. A
/// sentence in this file that states a fact the headers do not hold is a bug of
/// the same kind the whole arrangement exists to prevent.
///
/// Usage:
///   ax310_spec                write the document to stdout
///   ax310_spec --write PATH   write it to PATH
///   ax310_spec --check PATH   exit non-zero if PATH is not what would be written

#include <ax310/Protocol.hpp>
#include <ax310/Types.hpp>

#include <algorithm>
#include <cstdlib>
#include <fstream>
#include <iterator>
#include <print>
#include <span>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

using namespace ax310;

namespace
{

/// @param value A byte.
/// @return It as `0x` followed by two lowercase hex digits.
[[nodiscard]] std::string hex(std::uint8_t value)
{
    return std::format("0x{:02x}", value);
}

/// @param text A display string that may carry padding.
/// @return It without leading or trailing spaces.
[[nodiscard]] std::string_view trimmed(std::string_view text)
{
    while (!text.empty() && text.front() == ' ')
        text.remove_prefix(1);
    while (!text.empty() && text.back() == ' ')
        text.remove_suffix(1);
    return text;
}

/// @param name A name that may be empty.
/// @return The name, or an em dash so a table cell is never blank.
[[nodiscard]] std::string_view orDash(std::string_view name)
{
    return name.empty() ? std::string_view { "—" } : name;
}

/// @param encoding How a parameter is stored in its command's body.
/// @return How to say that in a table cell.
[[nodiscard]] std::string_view describeEncoding(protocol::ParameterEncoding encoding)
{
    switch (encoding)
    {
        case protocol::ParameterEncoding::SignedByte: return "signed byte";
        case protocol::ParameterEncoding::UnsignedByte: return "unsigned byte";
        case protocol::ParameterEncoding::UnsignedWordLE: return "unsigned 16, little-endian";
    }
    return "—";
}

/// @param address A property address.
/// @return How many bytes of it the connect sequence saves and puts back, said
///         the way a table cell should say it.
[[nodiscard]] std::string preservedLength(std::uint8_t address)
{
    for (auto const& row: protocol::PreservedAddresses)
        if (row.address == address)
            return row.length == 1 ? std::string { "yes, 1 byte" }
                                   : std::format("yes, {} bytes", row.length);
    return "no";
}

/// @param address A property address.
/// @return Whether writing it is refused.
[[nodiscard]] bool isDangerous(std::uint8_t address)
{
    return std::ranges::find(protocol::DangerousAddresses, address)
           != protocol::DangerousAddresses.end();
}

void writeSpec(std::ostream& out)
{
    using namespace ax310::protocol;

    // Jekyll front matter, so the same generated file is both the document in the
    // repository and the specification page on the site. Writing the page by hand
    // instead would put a second copy of every address somewhere nothing checks.
    std::println(out, "---");
    std::println(out, "layout: default");
    std::println(out, "title: Wire specification");
    std::println(out, "description: >-");
    std::println(out,
                 "  The AX310's register map, report layout and framed commands, generated from "
                 "the driver that implements them.");
    std::println(out, "---");
    std::println(out, "<!-- SPDX-License-Identifier: Apache-2.0 -->");
    std::println(out, "# AX310 wire specification");
    std::println(out, "");
    std::println(out,
                 "**Generated by `ax310_spec` from `src/ax310/Protocol.hpp` and "
                 "`src/ax310/Types.hpp`. Do not edit.**");
    std::println(out, "");
    std::println(out,
                 "Every address, length, offset, range, default and name below is read from the "
                 "constant that implements it, so none of them can disagree with the driver. "
                 "`ctest -R wire-specification` fails when this file and the headers have "
                 "parted; `ax310_spec --write docs/wire-protocol.md` brings them back together.");
    std::println(out, "");
    std::println(out,
                 "The sentences around the tables are prose, and prose is what drifts. Where one "
                 "makes a claim a table cannot hold -- an endianness, an ordering, a range -- "
                 "there is a test in `Protocol_test.cpp` that fails if it stops being true. "
                 "Those are tagged `[spec]`.");
    std::println(out, "");
    std::println(out,
                 "What is *not* here is the evidence. Why a register is believed to mean what "
                 "it means, which readings were wrong first, and what remains unknown live in "
                 "`AGENT.md` and `.agent/rules/`, because none of that is derivable from a "
                 "table.");
    std::println(out, "");

    // ---- USB -------------------------------------------------------------
    std::println(out, "## The two USB devices");
    std::println(out, "");
    std::println(out,
                 "One physical unit enumerates as two devices at once, not as two states of "
                 "one. Only the control device carries the deck's protocol.");
    std::println(out, "");
    std::println(out, "| Mode | Product id | HID interface |");
    std::println(out, "| --- | --- | --- |");
    for (auto const mode: { DeviceMode::Base, DeviceMode::Control })
    {
        auto const descriptor = descriptorFor(mode);
        std::println(out,
                     "| {} | `0x{:04x}` | {} |",
                     mode == DeviceMode::Control ? "Control" : "Base",
                     descriptor.productId,
                     descriptor.interfaceNumber);
    }
    std::println(out, "");

    // ---- Input report ----------------------------------------------------
    std::println(out, "## The input report");
    std::println(out, "");
    std::println(out,
                 "{} bytes, or {} when padded. hidapi prepends the report id for a device that "
                 "numbers its reports and not for one that does not, so both lengths arrive; "
                 "`protocol::reportPayload()` is the one place that decides which.",
                 ControlReportSize,
                 PaddedReportSize);
    std::println(out, "");
    std::println(out,
                 "The report is **mixed-endian**: touch coordinates are little-endian and the "
                 "audio meters are big-endian, in the same frame.");
    std::println(out, "");
    std::println(out, "| Offset | Field |");
    std::println(out, "| --- | --- |");
    std::println(out,
                 "| `{:#04x}` | event type; `{}` is a screen touch. The button bitmask on any "
                 "other report. |",
                 EventTypeOffset,
                 hex(ScreenTouchEventType));
    std::println(out, "| `{:#04x}` | touch flags — seven values seen, meaning unknown |", TouchFlagsOffset);
    std::println(out, "| `{:#04x}` | touch x, little-endian |", TouchXOffset);
    std::println(out, "| `{:#04x}` | touch y, little-endian |", TouchYOffset);
    std::println(out, "| `{:#04x}` | knob push bitmask |", KnobPushOffset);
    std::println(out, "| `{:#04x}` | knob capacitive-touch bitmask |", KnobTouchOffset);
    std::println(out,
                 "| `{:#04x}` | knob rotation counters, {} of them, relative rather than "
                 "positions |",
                 KnobValuesOffset,
                 KnobCount);
    std::println(out,
                 "| `{:#04x}` | audio meters: {} tracks × {} bytes — a left and a right, both "
                 "16-bit big-endian, full scale `{:#x}` |",
                 AudioMetersOffset,
                 AudioMeterCount,
                 AudioMeterStride,
                 AudioLevelFullScale);
    std::println(out, "| `{:#04x}` | checksum |", ChecksumOffset);
    std::println(out, "");
    std::println(out,
                 "The meters are one per track in the deck's printed knob order, and the deck "
                 "sends all {} of them on every report.",
                 AudioMeterCount);
    std::println(out, "");

    std::println(out, "### Bit masks");
    std::println(out, "");
    std::println(out, "| Button | Bit |");
    std::println(out, "| --- | --- |");
    for (auto const button: AllButtons)
        std::println(out, "| {} | `{}` |", indexOf(button) + 1, hex(ButtonBits[indexOf(button)]));
    std::println(out, "");
    std::println(out, "| Knob | Bit |");
    std::println(out, "| --- | --- |");
    for (auto const knob: AllKnobs)
        std::println(out, "| {} | `{}` |", nameOf(knob), hex(KnobBits[indexOf(knob)]));
    std::println(out, "");

    // ---- Property family -------------------------------------------------
    std::println(out, "## Property registers");
    std::println(out, "");
    std::println(out,
                 "A byte-addressed register space, reached with a feature report of "
                 "`[{}|{}] {} <address> <length> <values…>` — set and get. A reply carries the "
                 "kind at byte {}, the group at {}, the address at {}, the length at {} and the "
                 "values from {}.",
                 hex(static_cast<std::uint8_t>(CommandKind::Set)),
                 hex(static_cast<std::uint8_t>(CommandKind::Get)),
                 hex(PropertyGroup),
                 ReplyKindOffset,
                 ReplyGroupOffset,
                 ReplyAddressOffset,
                 ReplyLengthOffset,
                 ReplyValuesOffset);
    std::println(out, "");
    std::println(out, "| Address | Name | Preserved on connect | Writable |");
    std::println(out, "| --- | --- | --- | --- |");
    auto byAddress = std::vector(PropertyNames.begin(), PropertyNames.end());
    std::ranges::sort(byAddress, {}, &WireName::value);
    for (auto const& row: byAddress)
        std::println(out,
                     "| `{}` | {} | {} | {} |",
                     hex(row.value),
                     orDash(row.name),
                     preservedLength(row.value),
                     isDangerous(row.value) ? "**refused**" : "yes");
    std::println(out, "");
    std::println(out,
                 "{} addresses are read before the handshake and written back after it, because "
                 "the captured init sequence is somebody's saved configuration rather than an "
                 "initialisation. The longest is {} bytes.",
                 PreservedAddresses.size(),
                 MaxPreservedLength);
    std::println(out, "");
    std::print(out, "Writes are refused to:");
    for (auto const address: DangerousAddresses)
        std::print(out, " `{}`", hex(address));
    std::println(out, " — writing there once wedged a deck badly enough to need a power cycle.");
    std::println(out, "");

    std::println(out, "### Per-track levels");
    std::println(out, "");
    std::println(out,
                 "Two contiguous blocks of {} bytes, one per mix, addressed `base + track` in "
                 "knob order. A level is {} steps and one step is exactly {}%.",
                 KnobCount,
                 Level::MaxSteps,
                 Level::PercentPerStep);
    std::println(out, "");
    std::print(out, "| Mix | Base |");
    for (auto const knob: AllKnobs)
        std::print(out, " {} |", nameOf(knob));
    std::println(out, "");
    std::print(out, "| --- | --- |");
    for (std::size_t index = 0; index < KnobCount; ++index)
        std::print(out, " --- |");
    std::println(out, "");
    for (auto const mix: AllMixes)
    {
        auto const block =
            mix == MixId::Creator ? Property::CreatorMixLevels : Property::AudienceMixLevels;
        std::print(out, "| {} | `{}` |", nameOf(mix), hex(static_cast<std::uint8_t>(block)));
        for (auto const knob: AllKnobs)
            std::print(out, " `{}` |", hex(levelAddressOf(block, knob)));
        std::println(out, "");
    }
    std::println(out, "");

    // ---- Framed family ---------------------------------------------------
    std::println(out, "## Framed commands");
    std::println(out, "");
    std::println(out,
                 "The DSP chain uses a second family: `{} 0x00 <length> <command> <body…> "
                 "<checksum>`, {} bytes of overhead around a body of at most {}.",
                 hex(FramedCommandMarker),
                 FramedOverhead,
                 MaxFramedBodySize);
    std::println(out, "");
    std::println(out, "| Command | Name |");
    std::println(out, "| --- | --- |");
    for (auto const& row: FramedCommandNames)
        std::println(out, "| `{}` | {} |", hex(row.value), orDash(row.name));
    std::println(out, "");

    std::println(out, "### Parameters");
    std::println(out, "");
    std::println(out,
                 "{} of them, each one row of `protocol::Parameters`. A parameter located later "
                 "becomes one more row and appears in both interfaces with no other change.",
                 Parameters.size());
    std::println(out, "");
    std::println(out, "| Effect | Parameter | Command | Body offset | Encoding | Range | Unit |");
    std::println(out, "| --- | --- | --- | --- | --- | --- | --- |");
    for (auto const& row: Parameters)
    {
        std::println(out,
                     "| {} | {} | `{}` | {} | {} | {}…{} | {} |",
                     EffectNames[static_cast<std::size_t>(row.effect)],
                     row.name,
                     hex(static_cast<std::uint8_t>(row.command)),
                     row.bodyOffset,
                     describeEncoding(row.encoding),
                     row.minimum,
                     row.maximum,
                     orDash(trimmed(row.unit)));
    }
    std::println(out, "");
    std::println(out,
                 "The DSP chain has no read-back, so the driver keeps a known-good body per "
                 "parameterised command and edits it in place. {} such bodies are held.",
                 FramedDefaults.size());
    std::println(out, "");
    for (auto const& entry: FramedDefaults)
    {
        std::print(out,
                   "- `{}` ({}), {} bytes:",
                   hex(static_cast<std::uint8_t>(entry.command)),
                   orDash(nameIn(FramedCommandNames, static_cast<std::uint8_t>(entry.command))),
                   entry.length);
        for (std::size_t index = 0; index < entry.length; ++index)
            std::print(out, " `{:02x}`", entry.body[index]);
        std::println(out, "");
    }
    std::println(out, "");

    // ---- Screen ----------------------------------------------------------
    std::println(out, "## The screen");
    std::println(out, "");
    std::println(out,
                 "JPEG frames go out on the output endpoint in chunks of {} bytes: a {}-byte "
                 "header and {} bytes of payload.",
                 ScreenChunkSize,
                 ScreenChunkHeaderSize,
                 ScreenChunkPayloadSize);
    std::println(out, "");
    std::println(out, "| Offset | Field |");
    std::println(out, "| --- | --- |");
    std::println(out, "| `{:#04x}` | sequence number |", ScreenChunkSequenceOffset);
    std::println(out,
                 "| `{:#04x}` | {} bytes marking the last chunk of a frame — `{}` on the final "
                 "chunk, `0x00` on every other |",
                 ScreenChunkFinalOffset,
                 ScreenChunkFinalByteCount,
                 hex(ScreenChunkFinalMarker));
    std::println(out, "| `{:#04x}` | payload length, little-endian |", ScreenChunkLengthOffset);
    std::println(out,
                 "| `{:#04x}` | payload sum, little-endian — the 16-bit unsigned sum of the "
                 "chunk's payload bytes |",
                 ScreenChunkChecksumOffset);
    std::println(out, "");
    std::println(out,
                 "Without the final-chunk marker the deck accepts every chunk, reports no error "
                 "and never puts the frame on screen.");
    std::println(out, "");

    // ---- LEDs ------------------------------------------------------------
    std::println(out, "## Knob LED rings");
    std::println(out, "");
    std::println(out,
                 "A knob property is {} bytes, with the ring level at offset {}, {} at full. The "
                 "captured init sequence sets brightness `{}`.",
                 KnobPropertyLength,
                 KnobLedLevelOffset,
                 MaxKnobLedLevel,
                 hex(static_cast<std::uint8_t>(KnobLedBrightnessAtStartup)));
    std::println(out, "");
}

} // namespace

int main(int argc, char* argv[])
{
    auto const arguments = std::span { argv, static_cast<std::size_t>(argc) };

    std::ostringstream generated;
    writeSpec(generated);

    if (argc == 1)
    {
        std::print("{}", generated.str());
        return EXIT_SUCCESS;
    }

    auto const command = std::string_view { arguments[1] };
    if (argc != 3 || (command != "--check" && command != "--write"))
    {
        std::println(stderr, "usage: {} [--write PATH | --check PATH]", arguments[0]);
        return EXIT_FAILURE;
    }

    auto const path = std::string { arguments[2] };

    if (command == "--write")
    {
        std::ofstream file { path, std::ios::binary | std::ios::trunc };
        if (!file)
        {
            std::println(stderr, "could not write {}", path);
            return EXIT_FAILURE;
        }
        file << generated.str();
        std::println("wrote {}", path);
        return EXIT_SUCCESS;
    }

    std::ifstream file { path, std::ios::binary };
    if (!file)
    {
        std::println(stderr, "{} does not exist -- run: ax310_spec --write {}", path, path);
        return EXIT_FAILURE;
    }

    std::string const committed { std::istreambuf_iterator<char> { file },
                                  std::istreambuf_iterator<char> {} };
    if (committed == generated.str())
        return EXIT_SUCCESS;

    // Says which line first differs, because "the file changed" is not a lead.
    std::istringstream want { generated.str() };
    std::istringstream have { committed };
    std::string wantLine;
    std::string haveLine;
    for (int line = 1;; ++line)
    {
        bool const wantMore = static_cast<bool>(std::getline(want, wantLine));
        bool const haveMore = static_cast<bool>(std::getline(have, haveLine));
        if (!wantMore && !haveMore)
            break;
        if (wantMore != haveMore || wantLine != haveLine)
        {
            std::println(stderr, "{} is out of date, from line {}:", path, line);
            std::println(stderr, "  committed: {}", haveMore ? haveLine : "(end of file)");
            std::println(stderr, "  headers:   {}", wantMore ? wantLine : "(end of file)");
            break;
        }
    }
    std::println(stderr, "");
    std::println(stderr, "The wire specification is generated from Protocol.hpp and Types.hpp.");
    std::println(stderr, "Run: ax310_spec --write {}", path);
    return EXIT_FAILURE;
}
